language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
env:
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
